### ISSUE TITLE
Use :target to highlight linked line, instead of JavaScript

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-ripgrep#14]
https://twitter.com/loulouxiv/status/1332696241650737152
> Here is is a tip to simplify the highlighting of a linked line: you can get rid of this javascript by using the CSS :target pseudo-class
> https://developer.mozilla.org/en-US/docs/Web/CSS/:target

```css
:target {
  border: 2px solid black;
}
```
